project: "2019-01_folders"
year: 2019
month: "all"

##This is the array experiment differntially expressed genes
#experiment: 
#  first_experiment:
#  second_experiment:
#
##This is a path somewhere
#path: "../../../path/somewhere/"
#
##This is a parameter
#probe_map: FALSE
#
##These are samples with parameters
#SampleList:
#  sample_a:
#    gtf: "../../data/xxx_sample_a.gtf"
#    ip: "../views/yyy_sample_a.bam"
#    g: "hs"
#  sample_b:
#    gtf: "../../data/xxx_sample_b.gtf"
#    ip: "../../views/yyy_sample_b.bam"
#    g: "mm"