---
title: "PDF_scrap"
author: "Marcos Morgan"
date: "25/06/2017"
output: html_document
---

Load libraries
```{r, message=FALSE, warning=FALSE}
library(pdftools)
require(knitr)
library(dplyr)
library(tidyr)
```

Set Working directory
```{r}
opts_knit$set(root.dir = '')
```

```{r}
pdf_file <- "../data/Macosko_2015.pdf"
info <- pdf_info(pdf_file)
#head(info)
```

```{r}
text <- pdf_text(pdf_file)
show(text)
```

```{r}
fonts <- pdf_fonts(pdf_file)
show(fonts)
```

```{r}
files <- pdf_attachments(pdf_file)
show(files)
```

Scrap notes
```{r}
page       <- text[15]
split_page <- as.data.frame(unlist(strsplit(page, "Marcos Morgan"))) %>% separate('unlist(strsplit(page, "Marcos Morgan"))', c("a", "b", "c", "d", "e"), sep="\n")
show(page)
show(split_page)
```

```{r}
comments <- split_page %>% filter(grepl("Page", a)) %>% select(-b) %>% mutate(a = as.integer(gsub("Page", "", a))) %>%
                           rename(Page = a) %>% unite(comment, c(c, d, e), sep = " ") %>% 
                           mutate(comment = gsub("NA", "", comment))
show(comments)
```

Import bibliography
```{r, message=FALSE, warning=FALSE}
library(RefManageR)
```

```{r}
biblio <- ReadBib("/Users/Marcos/Dropbox/Lab/Marcos_files/Scripts_Data/scripts/short_scripts/scrap_pdfs/data/collections/collection.bib")
#biblio
biblio[1]$author
biblio[1]$abstract
biblio[1]$title
biblio[1]$file
```

```{r}

```




